source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'weather' do
pod 'Alamofire', '~> 4.0'
end

# Pods for testing
target 'weatherTests' do
inherit! :search_paths
pod 'Alamofire', '~> 4.0'
end

